### ISSUE TITLE
Is there a roadmap about the antwar ?

### ISSUE THREAD

**Issue by frankLife** [antwarjs/antwar#129]
Antwar is a good project with webpack and react-router. But I find it is wip somehow. 

Can we show a plan about this project to see some excellent features in future ?

**Comment by bebraw** [comment]
I'm currently refactoring it a bit (simpler configuration) and hope to get the work done very soon so I can start using the generator in places. I've actually pushed a lot of weight from the core during this process. This has given a nice degree of flexibility that I like. I'm also adding some tests in place so it's easier to contribute if someone wants to.

There's no official road map but I have at least the following concerns in mind:

* Performance - Now it generates initial bundle and then uses that to generate each page. I believe it would be better to parallelize this (worker process, nothing special) and generate a bundle per instance (less to parse). This won't help with Travis or single threaded platforms but it would likely help in my personal usage.
* Routing - The current approach doesn't give you that SPA feeling. I think a little different approach may be required. Possibly a router could be implemented on top of a generated site although I can also consider generating JSON etc. to load PWA style.
* Replace React with [rapscallion](https://github.com/FormidableLabs/rapscallion) - I gave this a go earlier but I hit some issue with rapscallion. When it's mature enough, moving to it during generation might be a good way to go.
* Incremental generation - Instead of generating the whole site always, it would be good to look into caching at least a part of it. Maybe things like **cache-loader** can help here. Caching is a difficult problem, though, and I may have to invent new ways to deal with it (compose a site out of fragments that are then invalidated based on change).

Especially the last items might not happen as I don't have to maintain big sites to warrant that style of work. That said, I have to push the performance somehow as a Travis build against the webpack site is far too slow. A part of that might be just a matter of configuration.

**Comment by frankLife** [comment]
It's good to be with the support of the backend(ssr) so that we can get SPA feeling 💯 . But I find the documentation need improving. This [configuration](https://antwar.js.org/docs/configuration/) is too simple. I find I must learn about it from source code of antwar. 😄

**Comment by bebraw** [comment]
Yeah, the documentation isn't in sync with the implementation at the moment. The source is the best option (esp. the site + smoketest). I imagine adding SSR is far easier now than before.

I've kept Antwar out of sight on purpose as there are far more robust alternatives out there as it's not cheap to support these kind of projects (no business model). 👍

**Comment by frankLife** [comment]
That's all right. Hope it will be better in future and I will focus on this project 👍
